### ISSUE TITLE
Works from wavlab

### ISSUE THREAD

**Issue by ftshijt** [ga642381/speech-trident#2]
It is great to know about the news! Many thanks for hosting the tutorial. Would like to suggest a few works from WAVlab for the tree!

- [WavLabLM](https://arxiv.org/abs/2309.15317)
- [VotLM](https://arxiv.org/abs/2309.07937)
- [MR-HuBERT](https://openreview.net/forum?id=kUuKFW7DIF)

They are all open-sourced under ESPnet.

**Comment by ga642381** [comment]
Thank you @ftshijt for providing these works!

I've already added them to the paper list.
