### ISSUE TITLE
Can we include ichigo?

### ISSUE THREAD

**Issue by tikikun** [ga642381/speech-trident#20]
Technically can be considered a type of speech LM

https://arxiv.org/abs/2410.15316
https://github.com/homebrewltd/ichigo

Demo: https://ichigo.homebrew.ltd/

**Comment by ga642381** [comment]
Ichigo looks awesome! I just tried the demo, and it works great. Thank you for open-sourcing Ichigo—it's incredibly valuable. I’ll add it to Speech Trident.
